name: tsplay.dev Server Docker Image

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Install OS Packages
      uses: mstksg/get-package@v1
      with:
        apt-get: happy libblas-dev liblapack-dev libgmp-dev

    - uses: actions/checkout@v1

    - name: Setup stack
      uses: mstksg/setup-stack@v1

    - name: Install dependencies
      run: |
        set -ex
        stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
        set +ex
      env:
        ARGS: "--resolver lts-15.5"
      working-directory: server

    - name: Build
      run: |
        set -ex
        stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
        set +ex
      env:
        ARGS: "--resolver lts-15.5"
      working-directory: server

    - name: Build
      run: |
        set -ex
        stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
        set +ex
      env:
        ARGS: "--resolver lts-15.5"
      working-directory: server

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        BINARY_PATH: ".stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/tsplay-exe/tsplay-exe"
      with:
        name: gillchristian/tsplay
        username: gillchristian
        password: ${{ secrets.docker_password }}
        workdir: server
        buildargs: BINARY_PATH
