name: 'Server: Cache persist'

on: 
  push:
    branches:
      - master
    paths:
      - 'server/**'
      - '.github/workflows/server-*'

jobs:
  cache_persist:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        plan:
          - { stack-lts: "14.27", resolver: "--resolver lts-14.27" }

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install OS Packages
      uses: mstksg/get-package@v1
      with:
        apt-get: happy libblas-dev liblapack-dev libgmp-dev

    - uses: actions/checkout@v1

    - name: Setup stack
      uses: mstksg/setup-stack@v1

    - name: Cache ~/.stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-stack-lts-${{ matrix.plan.stack-lts }}-${{ hashFiles('server/package.yaml') }}-${{ hashFiles('server/stack.yaml') }}-${{ hashFiles('server/stack.yaml.lock') }}

    - name: Install dependencies
      run: |
        set -ex
        stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
        set +ex
      env:
        ARGS: ${{ matrix.plan.resolver }}
      working-directory: server
